apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
spec:
  ports:
    - name: metrics
      port: 9308
      targetPort: 9308
  selector:
    app: kafka-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:latest
          command: ["--kafka.server=kafka:9092"]
          ports:
            - containerPort: 9308