apiVersion: batch/v1
kind: Job
metadata:
  name: queue-init-replicaset
spec:
  template:
    spec:
      containers:
        - name: queue-init-replicaset
          image: mongo:6.0
          command:
            - mongosh
            - "--host"
            - "queue-db-0.queue-db-service.default.svc.cluster.local:27017"
            - "--eval"
            - "rs.initiate({_id: 'rs-queue', members: [{_id:0, host: 'queue-db-0.queue-db-service.default.svc.cluster.local:27017'}, {_id:1, host: 'queue-db-1.queue-db-service.default.svc.cluster.local:27017'}, {_id:2, host: 'queue-db-2.queue-db-service.default.svc.cluster.local:27017'}]})"
      restartPolicy: OnFailure