apiVersion: v1
kind: Service
metadata:
  name: room-db-service
spec:
  ports:
    - name: room-db
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: room-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: room-db
spec:
  selector:
    matchLabels:
      app: room-db
  serviceName: "room-db-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: room-db
    spec:
      containers:
        - name: room-db
          image: mongo:6.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - name: room-db-volume
              mountPath: /data/db
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
    - metadata:
        name: room-db-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: mongo-storage
        resources:
          requests:
            storage: 1Gi